[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
